services:
  postgres:
    container_name: ozon-postgres
    image: postgres:14.5
    hostname: postgres
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_PORT=${PG_PORT}
      - POSTGRES_PASSWORD=${PG_USER}
      - POSTGRES_USER=${PG_PASSWORD}
    ports:
      - "54239:5432"
    networks:
      - ozon-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./db/migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:postgres@postgres:5432/ozon?sslmode=disable",
      "up"
    ]
    networks:
      - ozon-network

  ozon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ozon
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PG_ADDR: ${PG_ADDR}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DB: ${PG_DB}
    ports:
      - "8080:8080"
    networks:
      - ozon-network


volumes:
  pg_data:

networks:
  ozon-network:
    driver: bridge